import { Inter } from "next/font/google";
import "./globals.css";
import FooterWrapper from "@/components/FooterWarpper/FooterWarpper";
import NavStoreWrapper from "@/components/NavStoreWrapper/NavStoreWrapper";
import { UserProvider } from "@/context/UserContext";
import NavWrapper from "@/components/NavWrapper/NavWrapper";
import { SearchProvider } from "@/context/SearchContext";
import { QuantityOrderProvider } from "@/context/QuantityOrderProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className="relative">
        <UserProvider>
          <QuantityOrderProvider>
            <SearchProvider>
              <NavWrapper />
              <NavStoreWrapper />
              {children}
              <FooterWrapper />
            </SearchProvider>
          </QuantityOrderProvider>
        </UserProvider>
      </body>
    </html>
  );
}
