import { Inter } from "next/font/google";
import "./globals.css";
import FooterWrapper from "@/components/FooterWarpper/FooterWarpper";
import NavStoreWrapper from "@/components/NavStoreWrapper/NavStoreWrapper";
import { UserProvider } from "@/context/UserContext";
import NavWrapper from "@/components/NavWrapper/NavWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className="relative">
        <UserProvider>
          <NavWrapper />
          <NavStoreWrapper />
          {children}
          <FooterWrapper />
        </UserProvider>
      </body>
    </html>
  );
}
