import { Inter } from "next/font/google";
import "./globals.css";
import FooterWrapper from "@/components/FooterWarpper/FooterWarpper";
import NavStoreWrapper from "@/components/NavStoreWrapper/NavStoreWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative">
        <NavStoreWrapper/>
        {children}
        <FooterWrapper />
      </body>
    </html>
  );
}
